### ISSUE TITLE
Language Representation is Wrong

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#147]
In the top right navigation on Android, we show "OBS (en)", which is correct.  On iOS, this is only showing "EN", which is wrong.

**Comment by dwsolberg** [comment]
I thought that "OBS" was redundant because we were already in Open Bible Stories. With longer titles in the diglot state, things will get cut off when scrolling because everything moves to one line. It's no problem to do this, but I wanted to let you know of the negative effects. Let me know either way. Thanks, David

**Comment by jag3773** [comment]
I think Android and iOS should look the same on this point, they don't currently.  Let's go with the way the Android currently looks.

**Comment by dwsolberg** [comment]
PJ, could you change this on your end?

**Comment by PeeJWeeJ** [comment]
So we're going with the way iOS currently looks?

**Comment by jag3773** [comment]
No, I said "Let's go with the way the Android currently looks."

**Comment by dwsolberg** [comment]
Sorry, I missed that.

**Comment by dwsolberg** [comment]
Oka
