### ISSUE TITLE
Crashes when Opening Bible after Update

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#164]
I can't tell if the Bible texts actually updated or not, since I can't get in to see them.

**Comment by PeeJWeeJ** [comment]
This is because the app was using the links to save content, and for some reason the links changed, skipping number 40 (see screenshot) I'll change things so this is no longer an issue.

<img width="756" alt="screen shot 2015-12-22 at 12 47 04 pm" src="https://cloud.githubusercontent.com/assets/5498585/11963102/298e95dc-a8aa-11e5-8791-7918c237466c.png">

**Comment by PeeJWeeJ** [comment]
This issue should be fixed in the next beta
